# Generated by Django 5.2.6 on 2025-09-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NormalModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(
                    blank=True, max_length=100, null=True)),
                ("age", models.IntegerField()),
            ],
        ),
    ]
