# Generated by Django 5.2.6 on 2025-09-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0002_normalmodel_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="normalmodel",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="normalmodel",
            name="user_id",
            field=models.IntegerField(null=True),
        ),
    ]
